# Generated by Django 5.2.9 on 2025-12-17 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total loan amount (principal) issued to the borrower",
                        max_digits=12,
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Interest rate for the loan (e.g. 0.1 for 10%)",
                        max_digits=5,
                    ),
                ),
                (
                    "loan_start_date",
                    models.DateField(
                        help_text="Start date of the loan in YYYY-MM-DD format"
                    ),
                ),
                (
                    "number_of_payments",
                    models.PositiveIntegerField(
                        help_text="Total number of payments in the repayment schedule"
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        help_text='Payment periodicity (e.g. "1d", "5d", "2w", "3m")',
                        max_length=4,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the loan was created",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoanPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_number",
                    models.PositiveIntegerField(
                        help_text="Sequential number of the payment in the schedule (starting from 1)"
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(help_text="Scheduled date for this payment"),
                ),
                (
                    "principal",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Principal amount to be paid in this payment",
                        max_digits=12,
                    ),
                ),
                (
                    "interest",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Interest amount to be paid in this payment",
                        max_digits=12,
                    ),
                ),
                (
                    "is_principal_fixed",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the principal amount is fixed and should not be recalculated",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the payment record was created",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        help_text="Reference to the related loan",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="loan_schedules.loan",
                    ),
                ),
            ],
            options={
                "ordering": ["payment_number"],
                "unique_together": {("loan", "payment_number")},
            },
        ),
    ]
